version: '2'

services:

  nginx:
    image: nginx:alpine
    container_name: assignment2ssd
   
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./nginx/localhost.key:/etc/nginx/certs/localhost.key
    links:
      - php

  php:
    build: 
      context: ./dockerfiles/php/
      dockerfile: ./Dockerfile
    volumes:
        - ./code:/code
    links:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./schema.sql:/schema.sql
      - ./data.sql:/data.sql
    environment:
      POSTGRES_PASSWORD: assignment1dbadmin

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
